ANIME = ['CAADAgADphUAAuCjggefWVbc25y8SwI',
         'CAADAgADpxUAAuCjggc3Rrbz0slw-QI',
         'CAADAgADqBUAAuCjggffM9zsGXHlnAI',
         'CAADAgADqhUAAuCjggfhAAHKOPPTj1IC',
         'CAADAgADsBUAAuCjggfFxAscuqfs1gI',
         'CAADAgADtRUAAuCjggcfYCHGsd6p6QI',
         'CAADAgADsxUAAuCjggfr70QwStsejQI',
         'CAADAgADtBUAAuCjggcyCetXGf-GHAI',
         'CAADAgADthUAAuCjggdERi8xXtF-vQI',
         'CAADAgADtxUAAuCjggf6twXK99hfDAI',
         'CAADAgADuBUAAuCjggcPJZCwRcf9WwI',
         'CAADAgADuRUAAuCjggfneX6_voT0KwI',
         'CAADAgADuhUAAuCjggctpk-q4xQNnwI',
         'CAADAgADvBUAAuCjggdYP4LkycCt1AI',
         'CAADAgADvhUAAuCjggfTE145KhwGBwI',
         'CAADAgADvxUAAuCjggfuWIZAuHQidQI',
         'CAADAgADwRUAAuCjggdnzH_jATfkHQI',
         'CAADAgADxxUAAuCjggdkK5ZDT-yAFQI',
         'CAADAgADyRUAAuCjggdwExtKCc1Z-QI',
         'CAADAgADyhUAAuCjggeQLnYKiruNWgI',
         'CAADAgADyxUAAuCjgge9hwaqhK1vJQI',
         'CAADAgADzBUAAuCjggecUcfv3H1QEQI']
CATS = ['CAADAgADLwMAAuSkCAdd1VcqHQ6p1gI',
        'CAADAgAD6gEAAn1alAw7nvZ35b1SgQI',
        'CAADBAADrwMAAv4zDQZ8eK0KrlzoNAI',
        'CAADAgADLgEAAiMiBAZRz30OVpPL3wI',
        'CAADAgADGAADIyIEBnbKZ2xPTJ2TAg',
        'CAADAgADawEAAn1alAxO5uLbwnsAAWYC',
        'CAADAgADVQUAAn1alAwmfXYRHlu_QQI',
        'CAADAgADSgEAAn1alAxcGLbIREyRFgI',
        'CAADAgADQgEAAn1alAwTa-2zlPbhSAI',
        'CAADAgADNAEAAn1alAzI3CBcvVZ5VAI',
        'CAADAgADOAEAAn1alAymOJAOQDA7tQI',
        'CAADAgADSAEAAn1alAxxQw-clSWhYwI',
        'CAADAgADjQEAAn1alAztxdiGuFSIewI',
        'CAADAgADlwEAAn1alAx2qJNpA7OuNwI',
        'CAADAgAD5AEAAn1alAwtgbPFFtl52wI',
        'CAADAgADwQUAAn1alAxC1Wm6n0YvhQI',
        'CAADAgADtwUAAn1alAx96THQGyFXdAI',
        'CAADAgADwwUAAn1alAwxnk0eb-M8mQI',
        'CAADAgADuwUAAn1alAzMg2R91s08nwI',
        'CAADAgADGQQAAuSkCAdntZVXOGj0ygI',
        'CAADAgADZgMAAuSkCAe1zRdgW-_BkwI',
        'CAADAgADpQMAAuSkCAdV4tpHqOSqXQI',
        'CAADAgADDwMAAuSkCAcWzhMfyMev_gI']

rlist = ['one', 'two', 'three']

HI = 'CAADAgADPgADaJpdDBmx-BngWdVLAg'
