ANIME = ['CAADAgADphUAAuCjggefWVbc25y8SwI',
         'CAADAgADpxUAAuCjggc3Rrbz0slw-QI',
         'CAADAgADqBUAAuCjggffM9zsGXHlnAI',
         'CAADAgADqhUAAuCjggfhAAHKOPPTj1IC',
         'CAADAgADsBUAAuCjggfFxAscuqfs1gI',
         'CAADAgADtRUAAuCjggcfYCHGsd6p6QI',
         'CAADAgADsxUAAuCjggfr70QwStsejQI',
         'CAADAgADtBUAAuCjggcyCetXGf-GHAI',
         'CAADAgADthUAAuCjggdERi8xXtF-vQI',
         'CAADAgADtxUAAuCjggf6twXK99hfDAI',
         'CAADAgADuBUAAuCjggcPJZCwRcf9WwI',
         'CAADAgADuRUAAuCjggfneX6_voT0KwI',
         'CAADAgADuhUAAuCjggctpk-q4xQNnwI',
         'CAADAgADvBUAAuCjggdYP4LkycCt1AI',
         'CAADAgADvhUAAuCjggfTE145KhwGBwI',
         'CAADAgADvxUAAuCjggfuWIZAuHQidQI',
         'CAADAgADwRUAAuCjggdnzH_jATfkHQI',
         'CAADAgADxxUAAuCjggdkK5ZDT-yAFQI',
         'CAADAgADyRUAAuCjggdwExtKCc1Z-QI',
         'CAADAgADyhUAAuCjggeQLnYKiruNWgI',
         'CAADAgADyxUAAuCjgge9hwaqhK1vJQI',
         'CAADAgADzBUAAuCjggecUcfv3H1QEQI']
CATS = []

damnlist = ['Няк?', '*пускаю искры*', '*подпрыгнул*',
            '*вылизываю промежность*', '*purr purr*',
            '*ищу взглядом твою обувь*', '*смотрю в сторону*',
            '*убегаю*', '*смотрю в пустой угол*', '*зашипел*',
            '*свернулся клубочком*', 'Может погладишь, сука?',
            'Только поел, перестань', 'Давно обувь менял?',
            'Это потому что ты - няша', 'Что еще някнешь?',
            'Хорошего дня, няша!', 'Возможно ты прав',
            'Не имей сто друзей, а имей сто котов', 'А?',
            'Я тебе потом отвечу', 'Лениво отвечать',
            'Твоя мама - хорошая женщина', 'Твой папа - достойный мужчина']
